import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50">
      <div className="max-w-3xl mx-auto px-4 py-12">
        <div className="bg-white p-8 md:p-12 rounded-xl shadow-sm border border-slate-200">
          <h1 className="text-3xl font-bold text-navy mb-2">Terms of Service</h1>
          <p className="text-slate-500 text-sm mb-8">Last updated: July 2026</p>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-navy mb-3">1. Service Description</h2>
            <p className="text-slate-700 leading-relaxed mb-4">
              LexRedline provides an AI-powered contract review engine that analyzes legal documents, 
              flags potentially risky clauses, and suggests redlines. The Service uses artificial intelligence 
              and machine learning to identify patterns and provide recommendations based on its training data.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-navy mb-3">2. Not Legal Advice</h2>
            <div className="bg-amber-50 border-l-4 border-amber-500 p-4 mb-4 rounded-r">
              <p className="text-amber-900 font-bold text-sm uppercase tracking-wider mb-1">⚠ Important Disclaimer</p>
              <p className="text-amber-800 leading-relaxed">
                <strong>LexRedline is not a law firm, does not provide legal advice, and does not create an attorney-client relationship.</strong> 
                The analysis, risk scores, redline suggestions, and any other output generated by the Service are 
                <strong> for informational and reference purposes only</strong>. They do not constitute legal advice, 
                legal opinion, or a substitute for professional legal counsel.
              </p>
            </div>
            <p className="text-slate-700 leading-relaxed mb-4">
              You should not act or refrain from acting based on any output from LexRedline without first 
              consulting a qualified attorney licensed to practice in your jurisdiction. The accuracy, 
              completeness, and applicability of AI-generated contract analysis depends on many factors, 
              including the quality of the uploaded document, the specificity of your expectations, and 
              the limitations of the underlying AI models.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-navy mb-3">3. No Attorney-Client Relationship</h2>
            <p className="text-slate-700 leading-relaxed mb-4">
              Use of LexRedline does not create an attorney-client relationship between you and LexRedline, 
              its operators, or its affiliates. Communications, documents, and data submitted through the 
              Service are not protected by attorney-client privilege or the work product doctrine.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-navy mb-3">4. Limitations of AI Analysis</h2>
            <p className="text-slate-700 leading-relaxed mb-4">
              The AI models powering LexRedline have inherent limitations. They may:
            </p>
            <ul className="list-disc list-inside text-slate-700 space-y-2 mb-4">
              <li>Miss clauses or risks that a human reviewer would identify</li>
              <li>Flag clauses that are actually standard or acceptable in your jurisdiction</li>
              <li>Suggest redlines that are inappropriate for your specific situation</li>
              <li>Incorrectly interpret contract language due to formatting, scanning quality, or ambiguous wording</li>
              <li>Not account for recent changes in law or jurisdiction-specific requirements</li>
            </ul>
            <p className="text-slate-700 leading-relaxed">
              Always review the AI analysis critically and consult a qualified attorney for any legal matter.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-navy mb-3">5. User Responsibilities</h2>
            <p className="text-slate-700 leading-relaxed mb-4">
              You are solely responsible for:
            </p>
            <ul className="list-disc list-inside text-slate-700 space-y-2 mb-4">
              <li>Ensuring that you have the right to upload and analyze any documents you submit</li>
              <li>Reviewing and verifying all AI-generated analysis before acting on it</li>
              <li>Seeking professional legal advice for any contract decisions</li>
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>Complying with all applicable laws and regulations</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-navy mb-3">6. Data Handling & Privacy</h2>
            <p className="text-slate-700 leading-relaxed mb-4">
              Contracts and documents you upload are processed by our AI engine and stored securely. 
              We do not share your contract data with third parties except as necessary to provide the 
              Service (e.g., AI model providers). We implement reasonable security measures to protect 
              your data, but no system is 100% secure. By using the Service, you acknowledge that 
              uploaded documents are processed by third-party AI services.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-navy mb-3">7. Disclaimer of Warranties</h2>
            <p className="text-slate-700 leading-relaxed mb-4">
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT ANY WARRANTIES, 
              EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, 
              FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. LEXREDLINE DOES NOT 
              WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT ANY ANALYSIS 
              WILL BE ACCURATE OR COMPLETE.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-navy mb-3">8. Limitation of Liability</h2>
            <p className="text-slate-700 leading-relaxed mb-4">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, LEXREDLINE, ITS OPERATORS, DEVELOPERS, AND 
              AFFILIATES SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
              CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM OR RELATED TO YOUR USE OF THE SERVICE, 
              INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, BUSINESS INTERRUPTION, 
              LOSS OF DATA, OR LEGAL LIABILITIES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-navy mb-3">9. Contact</h2>
            <p className="text-slate-700 leading-relaxed">
              If you have questions about these Terms, please contact us through the Help feature 
              within the Service or via the Help page.
            </p>
          </section>

          <div className="mt-12 pt-6 border-t border-slate-200">
            <Link href="/" className="text-accent-blue hover:underline font-medium">
              ← Back to Home
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}